crime_project/crime_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crimes/', include('crimes.urls'))
]

crime_project/crimes/urls.py
from django.urls import path
from . import views
app_name="crimes"
urlpatterns = [
    path('', views.ListDepartments.as_view(), name='list_departments'),
    path('add/', views.NewDepartment.as_view(), name='add_department'),
    path('edit/<int:pk>', views.EditDepartment.as_view(), name='edit_department'),
]

crime_project/crimes/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Departments(models.Model):
    agency_name = models.CharField(max_length=200)
    state_name = models.CharField(max_length=100)
    latitude = models.CharField(max_length=100, null=True, blank=True)
    longitude = models.CharField(max_length=100, null=True, blank=True)

crime_project/crimes/forms.py
from django import forms
from .models import Departments


# RATING_CHOICES= [tuple([x,x]) for x in range(1, 6)]

# class RatingForm(forms.ModelForm):
#     rating = forms.IntegerField(label="Your Rating", widget=forms.Select(choices=RATING_CHOICES))
#     class Meta:
#         model=Rating
#         fields = ('rating',)

class AddDepartment(forms.ModelForm):
    class Meta:
        model = Departments
        fields = ('__all__')
        # widgets = {
        #     'brand_title': forms.TextInput(
        #         attrs={'class': 'brand', 'placeholder':'Enter Brand'}
        #     )
        #}    

crime_project/crimes/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from .models import Departments
from django.views.generic.list import ListView
from .forms import AddDepartment
from django.views.generic.edit import CreateView, UpdateView
# Create your views here.


class ListDepartments(ListView):
    template_name = "departments/list_departments.html"
    model = Departments
    context_object_name = 'departments'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #filtered = Departments.objects.exclude(latitude=None)[:10]
        filtered = Departments.objects.filter(agency_name='test')
        #hello = Departments.objects.filter(state_name='Delaware').values('agency_name')[:20]
        context['departments'] = filtered
        #context['test'] = hello
        return context

class NewDepartment(CreateView):
    model = Departments
    template_name = "departments/add_department.html"
    fields = ['agency_name', 'state_name', 'latitude', 'longitude']
    success_url = '/crimes/'

class EditDepartment(UpdateView):
    model = Departments
    template_name = "departments/edit_department.html"
    success_url = '/crimes/'
    form_class = AddDepartment


# def get_queryset(self):
#         # queryset = super().get_queryset()
#         # self.kwargs == {'pk': 1}
#         # self.model = Cars
#         return self.model.objects.filter(**self.kwargs)

crime_project/crimes/templates/departments/add_department.html
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Add Department">
        </form>

crime_project/crimes/templates/departments/edit_department.html
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Edit Department">
</form>

crime_project/crimes/templates/departments/list_departments.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>

        </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <table class="">
            <thead class="">
            <tr>
                <th>Agency</th>
                <th>State</th>
                <th>Latitude</th>
                <th>Longitude</th>
            </tr>
            </thead>
            <p>{{ test }}</p>
            {% for item in departments %}
            <tr>
                <td>{{ item.agency_name }}</td>
                <td>{{ item.state_name }}</td>
                <td>{{ item.latitude }}</td>
                <td>{{ item.longitude }}</td>
            </tr>
            {% endfor %}
        </table>
        <button><a href="{% url 'crimes:add_department' %}">Add Event</a></button>
       
        
        <script src="" async defer></script>
    </body>
</html>